# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: PreBuild
  
  pool:
    # name: "Azure-DO-Self-Hosted"
    # demands:
    #   - Agent.OS -equals Windows_NT
    vmImage: ubuntu-latest

  jobs:
  - job: Build
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'mvn clean package'
  - job: SCA
    dependsOn: Build
    steps:
      - task: NexusIqPipelineTask@1 
        inputs:
          nexusIqService: 'NEXUS IQ'
          organizationId: '8f0895dbdb664a7fa14e7c45120cf334'
          applicationId: 'iwa-java-ado'
          stage: 'Build'
          scanTargets: 'pom.xml'
          enableDebugLogging: true
  - job: SAST
    steps:
      - task: FortifyScanCentralSAST@7
        inputs:
          scanCentralCtrlUrl: 'https://ssc.nsth.net/scancentral-ctrl'
          scanCentralClientToken: '$(ScanCentral.ClientToken)'
          sscUrl: 'https://ssc.nsth.net/ssc'
          sscCiToken: '$(ScanCentral.SscCiToken)'
          uploadToSSC: true
          applicationName: 'IWA-Java'
          applicationVersion: 'v1.0'
          buildTool: 'mvn'
          email: 'pattaranan.j@nsth.demo'
    
 