# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: PreBuild
  pool:
    # name: "Azure-DO-Self-Hosted"
    # demands:
    #   - Agent.OS -equals Windows_NT
    vmImage: ubuntu-latest
  jobs:
  - job: SAST
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
          curl -L https://ssc.nsth.net/ssc/downloads/Fortify_SCA_23.1.0_linux_x64.run -o /tmp/Fortify_SCA_23.1.0_linux_x64.run
          curl -L https://ssc.nsth.net/ssc/downloads/fortify.license -o /tmp/fortify.license
          chmod a+x /tmp/Fortify_SCA_23.1.0_linux_x64.run /tmp/fortify.license
          ls -l /tmp
          whoami
    # - task: InstallFortifySCA@7
    #   inputs:
    #     InstallerPath: '/tmp/Fortify_SCA_23.1.0_linux_x64.run'
    #     VS2015: false
    #     LicenseFile: '/tmp/fortify.license'
    #     RunFortifyRulepackUpdate: true
    # - task: PowerShell@2
    #   displayName: Download Fortify SCA from Fotify SSC
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       Write-Host "Downloading SCA from SSC"
    #       $BaseUrl = "https://ssc.nsth.net/ssc/downloads"
    #       New-Item -ItemType directory -Path C:\SoftwareDownload
    #       $url = "$BaseUrl/Fortify_SCA_23.1.0_windows_x64.exe"
    #       Write-Host $url
    #       $output = "C:\SoftwareDownload\Fortify_SCA_23.1.0_windows_x64.exe"
    #       $wc = New-Object System.Net.WebClient
    #       $wc.DownloadFile($url, $output)
          
    #       Write-Host "Downloading fortify.license from SSC"
    #       $url = "$BaseUrl/fortify.license"
    #       $output = "C:\SoftwareDownload\fortify.license"
    #       Write-Host $url
    #       $wc = New-Object System.Net.WebClient
    #       $wc.DownloadFile($url, $output)
    #       Write-Host "===Downloading Completed==="
    #       dir C:\SoftwareDownload
    #       C:\SoftwareDownload\Fortify_SCA_23.1.0_windows_x64.exe --help
    # - task: InstallFortifySCA@7
    #   displayName: Install Fortify SCA on Agent
    #   inputs:
    #     InstallerPath: 'C:\SoftwareDownload\Fortify_SCA_23.1.0_windows_x64.exe'
    #     VS2015: false
    #     VS2022: true
    #     LicenseFile: 'C:\SoftwareDownload\fortify.license'
    #     RunFortifyRulepackUpdate: true
    # - task: PowerShell@2
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       Write-Host "Post SCA Install Script"
    #       Write-Host "##vso[task.prependpath]C:\Fortify\bin\"
    


