# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: PreBuild
  pool:
    # name: "Azure-DO-Self-Hosted"
    # demands:
    #   - Agent.OS -equals Windows_NT
    vmImage: windows-latest
  jobs:
  - job: SAST
    steps:
    - task: PowerShell@2
      displayName: Download Fortify SCA from Fotify SSC
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Downloading SCA from SSC"
          $BaseUrl = "https://ssc.nsth.net/ssc/downloads"
          New-Item -ItemType directory -Path C:\SoftwareDownload
          $url = "$BaseUrl/Fortify_SCA_22.2.0_windows_x64.exe"
          Write-Host $url
          $output = "C:\SoftwareDownload\Fortify_SCA_22.2.0_windows_x64.exe"
          $wc = New-Object System.Net.WebClient
          $wc.DownloadFile($url, $output)
          
          # Write-Host "Downloading fortify.license from SSC"
          # $url = "$BaseUrl/fortify.license"
          # $output = "C:\SoftwareDownload\fortify.license"
          # Write-Host $url
          # $wc = New-Object System.Net.WebClient
          # $wc.DownloadFile($url, $output)
          # Write-Host "===Downloading Completed==="
          # dir C:\SoftwareDownload
          # cat C:\SoftwareDownload\fortify.license
      enabled: true
    # - task: PowerShell@2
    #   displayName: Install Fortify SCA on Agent
    #   inputs:
    #     targetType: 'inline'
    #     script: 'C:\SoftwareDownload\Fortify_SCA_23.1.0_windows_x64.exe --mode unattended --unattendedmodeui minimal --fortify_license_path "fortify.license" --installdir "C:\Fortify\Fortify_SCA_and_Apps" --enable-components "ScanCentralClient"'
    #   enabled: true  
    - task: InstallFortifySCA@7
      displayName: Install Fortify SCA on Agent
      inputs:
        InstallerPath: 'C:\SoftwareDownload\Fortify_SCA_22.2.0_windows_x64.exe'
        VS2015: false
        ScanCentralClient: true
        LicenseFile: 'C:\SoftwareDownload\fortify.license'
        RunFortifyRulepackUpdate: true
 
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Post SCA Install Script"
          Write-Host "##vso[task.prependpath]C:\Fortify\bin\"
          Write-Host "##vso[task.prependpath]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
      enabled: true
    - task: PowerShell@2
      displayName: Build
      inputs:
        targetType: 'inline'
        script: 'mvn clean package'
      enabled: true  
    - task: FortifySCA@7
      inputs:
        applicationType: 'java'
        buildSourceVersion: '11'
        fortifySourceTranslate: './**/*.java'
        fortifyBuildId: 'iwa-java'
        scaVerbose: true
        scaDebug: true
        fortifyScanType: 'LocalScan'


